name: 'Spack'
description: 'Load a Spack package tree'
branding:
  icon: 'package'
inputs:
  spack_root:
    description: 'Root of Spack installation'
    required: false
    default: '/cvmfs/eic.opensciencegrid.org/packages/spack/current'
  environment:
    description: 'Spack environment to load'
    required: false
    default: ''
runs:
  using: "composite"
  steps: 
    - run: |
        echo "SPACK_ROOT=$SPACK_ROOT" >> $GITHUB_ENV
        echo "$SPACK_ROOT/bin" >> $GITHUB_PATH
        [ -z "${{ inputs.environment }}" ] || $SPACK_ROOT/bin/spack env activate --sh ${{ inputs.environment }} | tee | sed 's/export //;s/\;$//;/^alias.*$/d'
>> $GITHUB_ENV
      shell: bash
      env:
        SPACK_ROOT: ${{ inputs.spack_root }}
