name: 'Spack'
description: 'Load a Spack package tree'
branding:
  icon: 'package'
inputs:
  spack_root:
    description: 'Root of Spack installation'
    required: false
    default: '/cvmfs/eic.opensciencegrid.org/packages/spack/current'
  environment:
    description: 'Spack environment to load'
    required: false
    default: ''
runs:
  using: "composite"
  steps: 
    - run: |
        echo "SPACK_ROOT=$SPACK_ROOT" >> $GITHUB_ENV
        echo "$SPACK_ROOT/bin" >> $GITHUB_PATH
      shell: bash
      env:
        SPACK_ROOT: ${{ inputs.spack_root }}
    - run:
      - >
        $SPACK_ROOT/bin/spack env activate --sh ${{ inputs.environment }}
        | sed 's/export //;s/\;$//;/^alias.*$/d'
        | while read line ; echo $line >> $GITHUB_ENV ; done
      if: "${{ inputs.environment != '' }}"
      shell: bash
      env:
        SPACK_ROOT: ${{ inputs.spack_root }}
