name: Test setup-spack action (with environment)
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eic/setup-cvmfs@main
    - uses: eic/setup-spack@main
      with:
        environment: 'eic'
    - name: List packages in Spack
      run: |
        env | sort
        spack find
        cat $GITHUB_ENV
        cat $GITHUB_PATH
      shell: bash
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: variables
        path: |
          $GITHUB_ENV
          $GITHUB_PATH
