name: Test setup-spack action (minimal usage)
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eic/setup-cvmfs@main
    - uses: eic/setup-spack@main
      with:
        spack_root: /cvmfs/eic.opensciencegrid.org/packages/spack/current
    - name: Setup CernVM-FS
      run: |
        spack find
